org.gradle.jvmargs = -Xmx4G
org.gradle.parallel=true

unimined.auth.enabled=true
unimined.auth.storeCredentials=true

# Publishing
    modrinth_id = pZ2wrerK
    curseforge_id_forge = 403422
    curseforge_slug_forge = emotecraft-forge
    curseforge_id_fabric = 397809
    curseforge_slug_fabric = emotecraft
    hangar_id = emotecraft
    minecraft_release_versions = 26.2

# Properties
    minecraft_version = 26.2
    fabric_loader_version = 0.19.3
    neoforge_version = 26.2.0.32-beta

# Mod Properties
    mod_description = Play emotes in Minecraft\nOpen the menu to setup your fast-choose wheel\n\nYou can add custom emotes, and you can play these even if nobody else has them!\n\nSpecial thanks:\n- Kale Ko for creating emotes and help in the UI design\n\nMaintained by dima_dencep and ZigyTheBird
    version_base = 3.4.0
    archives_base_name = emotecraft

# Dependencies
    java_version = 25
    translationfallbacks_version = 1.2.0+mc.26.1-snapshot-10
    playeranimlib_version = 1.2.6+mc.26.2
    bendablecuboids_version = 2.0.1+mc.1.21.11
    modmenu_version = 20.0.0-beta.4
    fabric_api_version = 0.153.0+26.2
    searchables_version = 1.0.1
    concentus_version = 1.0.2
    geyser_version = 2.11.0-SNAPSHOT
    commonutils_version = 1.2.8
    redlanceemotes_version = 2.2.0
