package com.kosmx.emotecraftCommon.math;

public enum Ease {
    LINEAR, INSINE, OUTSINE, INOUTSINE, INCUBIC, OUTCUBIC, INOUTCUBIC, INQUAD, OUTQUAD, INOUTQUAD, INQUART, OUTQUART, INOUTQUART, INQUINT, OUTQUINT, INOUTQUINT, INEXPO, OUTEXPO, INOUTEXPO, INCIRC, OUTCIRC, INOUTCIRC, INBACK, OUTBACK, INOUTBACK, INELASTIC, OUTELASTIC, INOUTELASTIC, INBOUNCE, OUTBOUNCE, INOUTBOUNCE, CONSTANT
}
