plugins {
    id "com.gradleup.shadow"
    id "com.modrinth.minotaur"
}

architectury {
    platformSetupLoomIde()
    fabric()
}

loom {
    accessWidenerPath = project(":minecraft:archCommon").loom.accessWidenerPath
}

configurations {
    compileModule
    common
    commonModule

    common.extendsFrom commonModule
    compileModule.extendsFrom commonModule

    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentFabric.extendsFrom common
}

dependencies {
    modImplementation "net.fabricmc:fabric-loader:${rootProject.loader_version}"

    // Fabric API
    modImplementation(fabricApi.module("fabric-command-api-v2", rootProject.fabric_api_version))
    modImplementation(fabricApi.module("fabric-networking-api-v1", rootProject.fabric_api_version))
    modImplementation(fabricApi.module("fabric-key-binding-api-v1", rootProject.fabric_api_version))
    modImplementation(fabricApi.module("fabric-lifecycle-events-v1", rootProject.fabric_api_version))

    commonModule(project(':executor')) {transitive false}
    commonModule(project(':emotesAPI')) {transitive false}
    commonModule(project(':emotesServer')) {transitive false}
    commonModule(project(':emotesAssets')) {transitive false}

    modRuntimeOnly(fabricApi.module("fabric-screen-api-v1", rootProject.fabric_api_version))
    modImplementation("com.terraformersmc:modmenu:${rootProject.modmenu_version}") {
        exclude group: "net.fabricmc.fabric-api"
    }

    include modImplementation("io.github.kosmx.bendy-lib:bendy-lib-fabric:${rootProject.bendylib_version}")
    include modImplementation("dev.kosmx.player-anim:player-animation-lib-fabric:${rootProject.player_animator_version}")

    common(project(path: ":minecraft:archCommon", configuration: "namedElements")) { transitive false }
    compileModule(project(path: ":minecraft:archCommon", configuration: "transformProductionFabric")) { transitive false }
}


processResources {
    inputs.property "version", project.version
    inputs.property "description", rootProject.mod_description

    filesMatching("fabric.mod.json") {
        expand "version": project.version, "description": rootProject.mod_description
    }
}


// ensure that the encoding is set to UTF-8, no matter what the system default is
// this fixes some edge cases with special characters not displaying correctly
// see http://yodaconditions.net/blog/fix-for-java-file-encoding-problems-with-gradle.html
tasks.withType(JavaCompile) {
    options.encoding = "UTF-8"
}

// Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
// if it is present.
// If you remove this task, sources will not be generated.

shadowJar{
    configurations = [project.configurations.compileModule]
    archiveClassifier.set("fabric-dev")
}

remapJar{
    injectAccessWidener = true
    inputFile.set shadowJar.archiveFile
    archiveClassifier.set("fabric")
}

jar {
    archiveClassifier.set("dev")
}

components.java {
    withVariantsFromConfiguration(project.configurations.shadowRuntimeElements) {
        skip()
    }
}


// configure the maven publication
publishing {
    publications {
        mavenJava(MavenPublication) {
            // add all the jars that should be included when publishing to maven
            artifact(jar) {
                builtBy remapJar
            }
            //artifact("${project.buildDir.absolutePath}/libs/${archivesBaseName}-${project.version}.jar"){
            //	builtBy remapJar
            //}
            artifact(remapJar) {
                builtBy remapJar
            }
        }
    }

    // select the repositories you want to publish to
    repositories {
        // uncomment to publish to the local maven
        mavenLocal()
    }
}

if (keysExists) {
    modrinth {
        versionType = project.cfType

        uploadFile = remapJar

        token = project.keys.modrinth_token
        // Get the GitHub Access Token you got from the basics part of this tutorial.
        projectId = "pZ2wrerK" // Enter your modrinth mod ID here.
        //System.out.println("Enter the version number:");
        versionNumber = "${project.mod_version}+${project.minecraft_version}-fabric"
        versionName = "${project.mod_version}"

        gameVersions = ["1.21.1"]
        changelog = changes
        loaders = ["fabric", "quilt"]
        failSilently = false

        dependencies {
            required.project "fabric-api"
            optional.project "modmenu"
            embedded.project "bendy-lib"
            embedded.project "playeranimator"
        }
    }
}
